namespace: 'reading'

paths:
  requireLib: 'require'
  app:        'backbone'
  extend:     'libs/extend'
  jquery:     'libs/jquery'
  jquery_ui:  'libs/jquery_ui'
  underscore: 'libs/lodash_extended'
  backbone:   'libs/backbone_extended'
  handlebars: 'libs/handlebars_extended'

modules:
  - name: 'reading'
    include: ['requireLib', 'web/init']
    create: true
