namespace: 'r_require'
preserveLicenseComments: false

uglify:
  max_line_length: 1000

paths:
  requireLib: 'require'
  app:        'backbone'
  extend:     'libs/extend'
  jquery:     'libs/jquery'
  jquery_ui:  'libs/jquery_ui'
  underscore: 'libs/lodash_extended'
  backbone:   'libs/backbone_extended'
  handlebars: 'libs/handlebars_extended'

modules:
  - name: 'web/loader'
    include: ['requireLib','web/init']
    exclude: ['jquery','jquery_ui','underscore','backbone','handlebars']
    create: true
  - name: 'bookmarklet/loader'
    include: ['requireLib','bookmarklet/init']
    exclude: ['jquery','jquery_ui','underscore','backbone','handlebars']
    create: true
  - name: 'libs/jquery'
  - name: 'libs/jquery_ui'
  - name: 'libs/lodash_extended'
    include: ['extend/underscore/log','extend/underscore/iso_date_string']
  - name: 'libs/backbone_extended'
    include: ['app/addons/nest_collection','app/addons/sync','app/models/model','app/collections/collection']
    exclude: ['jquery','underscore','handlebars']
  - name: 'libs/handlebars_extended'
    include: ['extend/handlebars/helpers']
    exclude: ['jquery','underscore','backbone']
  - name: 'ie/html5'

priority: ['jquery','jquery_ui','underscore','backbone','handlebars']
