# Config options can be found here:
# https://github.com/jrburke/r.js/blob/master/build/example.build.js

# NOTE
# For whatever reason, if you don't add `create: true` to the
# second module that's built, requireLib will be included out
# of order and the JS will fail

namespace: r_require
preserveLicenseComments: false

paths:
  requireLib: require
  app:        backbone
  extend:     libs/extend
  jquery:     libs/jquery_extended
  jquery_ui:  libs/jquery_ui
  underscore: libs/lodash_extended
  backbone:   libs/backbone_extended
  handlebars: libs/handlebars
  pusher:     libs/pusher_extended

modules:
  - name: web/loader
    include:
      - requireLib
      - app/routers/all
    excludeShallow:
      - libs/jquery
      - libs/jquery_ui
      - libs/lodash
      - libs/backbone
      - libs/handlebars
      - libs/pusher

  - name: bookmarklet/loader
    create: true
    include:
      - requireLib
      - bookmarklet/real_loader
    excludeShallow:
      - libs/jquery
      - libs/jquery_ui
      - libs/lodash
      - libs/backbone
      - libs/handlebars
      - libs/pusher

  - name: libs/jquery

  - name: libs/jquery_ui
    exclude:
      - jquery

  - name: libs/lodash

  - name: libs/backbone
    exclude:
      - jquery
      - underscore

  - name: libs/handlebars

  - name: libs/pusher

optimize: uglify2 # set to none for testing

# NOTE uglify2 config is namespaced under uglify2, though many docs show just uglify
#uglify2:
  #sequences: false
