namespace: 'r_require'

paths:
  requireLib: 'require'
  app:        'backbone'
  extend:     'libs/extend'
  jquery:     'libs/jquery'
  jquery_ui:  'libs/jquery_ui'
  underscore: 'libs/lodash_extended'
  backbone:   'libs/backbone_extended'
  handlebars: 'libs/handlebars_extended'

modules:
  - name: 'web/loader'
    include: ['requireLib', 'baseUrl', 'web/init']
    exclude: ['jquery','jquery_ui','underscore','backbone','handlebars']
    create: true
  - name: 'bookmarklet/loader'
    include: ['requireLib', 'baseUrl', 'bookmarklet/init']
    exclude: ['jquery','jquery_ui','underscore','backbone','handlebars']
    create: true
  - name: 'jquery'
  - name: 'jquery_ui'
  - name: 'underscore'
    include: ['libs/lodash_extended']
  - name: 'handlebars'
    include: ['libs/handlebars_extended']
  - name: 'backbone'
    include: ['libs/backbone_extended']
    exclude: ['jquery','underscore']

priority: ['jquery','jquery_ui','underscore','backbone','handlebars']
