# Config options can be found here:
# https://github.com/jrburke/r.js/blob/master/build/example.build.js

# NOTE
# For whatever reason, if you don't add `create: true` to the
# second module that's built, requireLib will be included out
# of order and the JS will fail

namespace: r_require
preserveLicenseComments: false

paths:
  requireLib: require
  extend:     libs/extend
  text:       libs/extend/require/text
  jquery:     libs/jquery_extended
  jquery_ui:  libs/jquery_ui
  underscore: libs/lodash_extended
  backbone:   libs/backbone_extended
  mustache:   libs/mustache
  pusher:     libs/pusher/pusher_extended

modules:
  - name: web/init
    include:
      - requireLib
      - app/routers/all
    excludeShallow:
      - libs/jquery
      - libs/jquery_ui
      - libs/lodash
      - libs/backbone
      - libs/mustache
      - libs/pusher/pusher

  - name: bookmarklet/init
    create: true
    include:
      - requireLib
      - bookmarklet/real_init
    excludeShallow:
      - libs/jquery
      - libs/jquery_ui
      - libs/lodash
      - libs/backbone
      - libs/mustache
      - libs/pusher/pusher

  - name: libs/jquery

  - name: libs/jquery_ui
    exclude:
      - jquery

  - name: libs/lodash

  - name: libs/backbone
    exclude:
      - jquery
      - underscore

  - name: libs/mustache

  - name: libs/pusher/pusher

  # NOTE - silliness
  - name: etc/clippy
    exclude:
      - jquery

optimize: uglify2 # set to none for testing

# NOTE uglify2 config is namespaced under uglify2, though many docs show just uglify
#uglify2:
  #sequences: false
